spring.application.name = Transmigrator-App 
server.port=8081

server.erroe.whitelable.enabled = false
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL (optional)
spring.jpa.show-sql=true

# H2 console
spring.h2.console.enabled=true


# 2705 Actuator exposure
management.endpoints.web.exposure.include=*

# 2705 Show detailed health info
management.endpoint.health.show-details=always

# 2705 App info (optional)
management.info.env.enabled=true
info.app.name=Transmigrator-App
info.app.description=Event Driven Decision Engine
info.app.version=1.0
